### ISSUE TITLE
Bitcode Error On Archive

### ISSUE THREAD

**Issue by justin** [Leanplum/Leanplum-iOS-SDK#17]
Hi,

Using the 1.7 SDK we are getting this error. Not sure if it's related to a change you all made or us bumping up to Xcode 8.3 (or both)? 

> ld: bitcode bundle could not be generated because '/Users/justin/Development/TEDapp/Carthage/Build/iOS/Leanplum.framework/Leanplum' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64

**Comment by gigasmile** [comment]
Somehow when we upgraded our XCode to 8.3 we lost bitcode support. If you explicitly disable bitcode, it will work as expected. We are looking into this. Will likely release 1.7.1 with XCode 8.3 fixes. 

Note that 1.7.0 is 1.6.0 with 10.3 features. If you are not using 10.3 features (App Rating, App Icon Change), please use 1.6.0.

**Comment by jaz-ah** [comment]
yes we're having the same issue w/ 1.7.0 thanks.

**Comment by benmarten** [comment]
This turned out to be introduced by a change in xcodebuild regarding bitcode flag. Fix will be available in 1.7.1 scheduled for 4/24.

**Comment by ikzjfr0** [comment]
i have the same problem for 1.7.0 but it's on Xcode8.2.1 
When i rolled back to 1.6.0, it works fine.

**Comment by gigasmile** [comment]
This is because 1.7 is built with XCode 8.3 which introduced this bug. It's fixed internally and is in QA right now. The next release is scheduled for 4/24.

**Comment by ikzjfr0** [comment]
@gigasmile thanks, that makes sense :)

**Comment by brunobar79** [comment]
1.7.1  was supposed to be released yesterday but you ended up releasing 1.7.0 with no bitcode support.  When is that gonna happen?

**Comment by gigasmile** [comment]
1.7.0 was released on March 28. You can see all the releases [here](https://support.leanplum.com/hc/en-us/articles/115000172423-iOS-SDK-release-notes).
You can use 1.6.0 which is equivalent to 1.7.0 but without the 10.3 features.

We are going to skip 1.7.1 and will release 2.0.0 soon. It's currently in QA. 
As of why it was re-released yesterday, you can see my comment here: https://github.com/Leanplum/Leanplum-iOS-SDK/issues/19#issuecomment-297075592

**Comment by brunobar79** [comment]
We've been pushing a release until today because we were waiting for the in-app review prompts via dashboard  feature but it looks like you guys have changed your plans and I assume that 2.0 is coming with breaking changes (major version release)  which it's not cool cause if that's the case, it's definitely gonna affect our roadmap... 

Just for the record, we are a paid customer with a +1 year relationship.

**Comment by aishaamajd** [comment]
Bruno,
We apologize for the inconvenience. The planned release date 2/24 for 2.0.0 unfortunately was delayed because of temporarliy limited resources in our QA team.
We are currently in the process of open sourcing the SDK and we will publish a roadmap for future releases soon too. This will hopefully ease the planning on your side. Nevertheless we can never guarantee to make a release date 100% because of unforseen issues or bugs.
The upcoming 2.0.0 release will be breaking only because we separated the UIEditor from the main SDK. Hence if you were not using the UIEditor there are not any breaking changes. If you were using the UIEditor then the only step required is to add the additional new library.

Lets set up some time to discuss your roadmap and how we can help you. I'll be sending you an email shortly.

**Comment by gigasmile** [comment]
This issue is fixed on 2.0.0. Sorry for the delay.
