### ISSUE TITLE
Unable to build a framework using Carthage

### ISSUE THREAD

**Issue by volkdmitri** [Leanplum/Leanplum-iOS-SDK#239]
Currently, the framework is delivered as a pre-compiled framework. Our team builds dependencies on our own (as a part of a workspace), so we use `--no-build` Carthage flag. But since `.xcodeproj` is missed we can not add the project to the workspace. SDK source code is available since version `2.0.1`, so clients can checkout source code and build the framework on their own. Note that Carthage will only build Xcode schemes that are shared from your `.xcodeproj` ([Supporting Carthage for your framework](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework)). Could you please add a missed `.xcodeproj`?

**Comment by hrishileanplum** [comment]
Hi @volkdmitri  thank you for the suggestion. We have added this task in our review list and would get back to you soon.

**Comment by iamariffikri** [comment]
@hrishileanplum We are using Carthage with `--no-use-binaries` to compile and build dependencies locally. This is seems not supported by your library where it only support pre-compiled binary to my attempts. It will be great if you are able to support `--no-use-binaries`

## Expected Behavior

Build successful.

## Actual Behavior

Unable to build `Leanplum-iOS-SDK` via Carthage. Carthage returns error: `Dependency "Leanplum-iOS-SDK" has no shared framework schemes`

## Steps to Reproduce the Problem

  1. Include `github "Leanplum/Leanplum-iOS-SDK"`
  2. Run `carthage build --no-use-binaries`
  3. Error `Dependency "Leanplum-iOS-SDK" has no shared framework schemes`

## Specifications

  - Version: 2.2.1
  - Platform: iOS

**Comment by mokagio** [comment]
🎉
