### ISSUE TITLE
Please provide a way to disable/stop the SDK

### ISSUE THREAD

**Issue by st3fan** [Leanplum/Leanplum-iOS-SDK#27]
(Mozilla / Firefox)

Please provide a way to stop the disable/stop the SDK

The rationale for this change is as follows: in Firefox we have have a user setting called *Send Anonymous Usage Data*. When this option is disabled, Firefox will immediately stop sending Telemetry and will also disable another SDK that we use in the product. At that point nothing is tracked or sent to telemetry servers / services.

We will file a pull request as a starting point for this issue.

**Comment by benmarten** [comment]
sounds good. pr's welcome :)

**Comment by alexisoyama** [comment]
I remember having an email about this. Using the enableTestMode method will essentially stop the sdk from that point on. It will not connect to the server and additional data will not be stored. Let me know if you want something more specific, otherwise will close it.

**Comment by alexisoyama** [comment]
Closing this. Please reopen if you need something more specific.

**Comment by Sdaswani** [comment]
Can we re-open this? We would like a supported way to stop the SDK, even if it's just setting test mode. At the moment our code doesn't read straightforwardly but if we had an API there would be something documented in the SDK docs.

**Comment by alexisoyama** [comment]
That makes sense. It's not an issue but more of a feature request. Can you talk to your CSM about this? They will talk to the Product team and make a feature request. I can mention it to them too but you'll have a better chance getting this in by talking to CSM directly.

**Comment by Sdaswani** [comment]
Yes I brought this up to Evan yesterday and he told me he is going to circle back with Product.

**Comment by st3fan** [comment]
@alexisoyama What is the status of this issue? Curious if this was discussed internally?

**Comment by alexisoyama** [comment]
@st3fan Sorry, i will not know. All feature requests are handled by CSM and Product.

**Comment by alexisoyama** [comment]
You can talk more with CSM / Product, but I'm personally hesitant with this request. We don't want other customers accidentally calling this method. Let's say we make a method called `[Leanplum stop]`. It can be confusing with `[Leanplum pause]`. `setTestMode` on the other hand does not sound like it is for production. 

Since the functionality is there, may i suggest using a Category for this? 
This way you can name it whatever you want and make it readable.

**Comment by mcomella** [comment]
> We don't want other customers accidentally calling this method. 
> Let's say we make a method called [Leanplum stop]. It can be confusing with [Leanplum pause].

@alexisoyama What if the method was called, `Leanplum.setEnabled(boolean)` or `Leanplum.setTrackingEnabled`? Do you think customers may still accidentally call this method? I wonder if this is a naming issue.

> setTestMode on the other hand does not sound like it is for production.

fwiw, using the `setTestMode` method also concerns me because it doesn't sound like it's a production method:
- Is it guaranteed to be supported in the future?
- Since it is intended for tests, is it more likely to have bugs in future releases (e.g. it's accidentally not added to new methods) than other production methods?

`setTestMode` also concerns me because the method name and its documentation don't make the same guarantees as a `setEnabled` would which are ones we want. The documentation (on Android) says, "This prevents Leanplum from communicating with the server." However, we also want to guarantee tracking is disabled while Leanplum is disabled so that if the user turns off Leanplum, interacts with the product, and re-enables Leanplum, the interactions they performed while Leanplum is disabled are not recorded to disk and then uploaded to the server when Leanplum is re-enabled. On Android, afaict, the code has this behavior but is it guaranteed in future iterations?
